services:
  - type: web
    name: swan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    packages:
      - google-chrome-stable